### PR TITLE
fix a define crap.

### PR DESCRIPTION
**Pull request by EternalWind**

### CODE REVIEW

**Comment by svenstaro** [comment]
This breaks it for dynamic builds because no symbols can be imported anymore.

**Comment by EternalWind** [comment]
Just remove __declspec(dllimport) while __declspec(dllexport) still there because you can't import a function like __declspec(dllimport) void function(){ do something} and __declspec(dllimport) is not so necessary for importing for some degree. See here: http://support.microsoft.com/kb/815647

**Comment by svenstaro** [comment]
Oh I see. Mh then still, perhaps it would be more proper to just export the declaration then. Can you do that?

**Comment by svenstaro** [comment]
Also you should probably make this request from and against master because it is a fix and not a feature. Small things like these can be merged directly.

By the way, you should delete your universal feature branch "cool-feature" and give it a proper name that is befitting to the actual feature you are developing.

**Comment by svenstaro** [comment]
Closing this since I have fixed it properly.

**Pull request closed without merging**
